# author:Lenovo
# datetime:2023/3/2 19:38
# software: PyCharm
# project:pytorch项目



a="MILLEVNNRIIEETLALKFENAAAGNKPEAVEVTFADFDGVLYHISNPNGDKTKVMVSIS"
b="LEVNNRIIEETLALKFENAAAGNKPEAVE"
c="MILLEVNNRIIEETLALKFENAAAGNKPEAVEVTFADFDGVLYHISNPNGDKTKVMVSISLKFYKELQAHGADELLKRVYGSFLVNPESGYNVSLLYDLENLPASKDSIVHQAGMLKRNCFASVFEKYFQFQEEGKEGENRAVIHYRDDETMYVESKKDRVTVVFSTVFKDDDDVVIGKVFMQEFKEGRRASHTAPQVLFSHREPPLELKDTDAAVGDNIGYITFVLFPRHTNASARDNTINLIHTFRDYLHYHIKCSKAYIHTRMRAKTSDFLKVLNRARPDAEKKEMKTITGKTFSSR"

kcr="RGGKAEDKEWMPVTKLGRLVKDMKIKSLE"
print("kcr:",len(kcr))

x=25 * 29
print(x)

print(len(b))
print(len(a))
print(len(c))